import 'package:flutter/material.dart';

abstract class AppColors {
  // ─── Light Theme (Metropolis Cairo) ─────────────────────────────────────────
  static const Color surface = Color(0xFFFCF9F8);
  static const Color surfaceDim = Color(0xFFDCD9D9);
  static const Color surfaceBright = Color(0xFFFCF9F8);
  static const Color surfaceContainerLowest = Color(0xFFFFFFFF);
  static const Color surfaceContainerLow = Color(0xFFF6F3F2);
  static const Color surfaceContainer = Color(0xFFF0EDEC);
  static const Color surfaceContainerHigh = Color(0xFFEBE7E7);
  static const Color surfaceContainerHighest = Color(0xFFE5E2E1);
  static const Color surfaceVariant = Color(0xFFE5E2E1);
  static const Color onSurface = Color(0xFF1C1B1B);
  static const Color onSurfaceVariant = Color(0xFF414750);
  static const Color inverseSurface = Color(0xFF313030);
  static const Color inverseOnSurface = Color(0xFFF3F0EF);
  static const Color outline = Color(0xFF727781);
  static const Color outlineVariant = Color(0xFFC1C7D2);
  static const Color primary = Color(0xFF003E6F);
  static const Color onPrimary = Color(0xFFFFFFFF);
  static const Color primaryContainer = Color(0xFF005596);
  static const Color onPrimaryContainer = Color(0xFFA4CAFF);
  static const Color inversePrimary = Color(0xFFA2C9FF);
  static const Color surfaceTint = Color(0xFF1B60A2);
  static const Color secondary = Color(0xFFBB0014);
  static const Color onSecondary = Color(0xFFFFFFFF);
  static const Color secondaryContainer = Color(0xFFE41F25);
  static const Color onSecondaryContainer = Color(0xFFFFFBFF);
  static const Color tertiary = Color(0xFF00471F);
  static const Color onTertiary = Color(0xFFFFFFFF);
  static const Color tertiaryContainer = Color(0xFF00612D);
  static const Color onTertiaryContainer = Color(0xFF5CE184);
  static const Color error = Color(0xFFBA1A1A);
  static const Color onError = Color(0xFFFFFFFF);
  static const Color errorContainer = Color(0xFFFFDA76);
  static const Color onErrorContainer = Color(0xFF93000A);
  static const Color background = Color(0xFFFCF9F8);
  static const Color onBackground = Color(0xFF1C1B1B);

  // ─── Dark Theme (Cairo Transit Premium) ─────────────────────────────────────
  static const Color darkSurface = Color(0xFF0F131C);
  static const Color darkSurfaceDim = Color(0xFF0F131C);
  static const Color darkSurfaceBright = Color(0xFF353943);
  static const Color darkSurfaceContainerLowest = Color(0xFF0A0E17);
  static const Color darkSurfaceContainerLow = Color(0xFF181C25);
  static const Color darkSurfaceContainer = Color(0xFF1C2029);
  static const Color darkSurfaceContainerHigh = Color(0xFF262A34);
  static const Color darkSurfaceContainerHighest = Color(0xFF31353F);
  static const Color darkOnSurface = Color(0xFFDFE2EF);
  static const Color darkOnSurfaceVariant = Color(0xFFC1C6D7);
  static const Color darkInverseSurface = Color(0xFFDFE2EF);
  static const Color darkInverseOnSurface = Color(0xFF2C303A);
  static const Color darkOutline = Color(0xFF8B90A0);
  static const Color darkOutlineVariant = Color(0xFF414755);
  static const Color darkSurfaceTint = Color(0xFFADC6FF);
  static const Color darkPrimary = Color(0xFFADC6FF);
  static const Color darkOnPrimary = Color(0xFF002E69);
  static const Color darkPrimaryContainer = Color(0xFF4B8EFF);
  static const Color darkOnPrimaryContainer = Color(0xFF00285C);
  static const Color darkInversePrimary = Color(0xFF005BC1);
  static const Color darkSecondary = Color(0xFF53E16F);
  static const Color darkOnSecondary = Color(0xFF003911);
  static const Color darkSecondaryContainer = Color(0xFF05B046);
  static const Color darkOnSecondaryContainer = Color(0xFF003A11);
  static const Color darkTertiary = Color(0xFFFFB4AA);
  static const Color darkOnTertiary = Color(0xFF690003);
  static const Color darkTertiaryContainer = Color(0xFFFF5545);
  static const Color darkOnTertiaryContainer = Color(0xFF5C0002);
  static const Color darkError = Color(0xFFFFB4AB);
  static const Color darkOnError = Color(0xFF690005);
  static const Color darkErrorContainer = Color(0xFF93000A);
  static const Color darkOnErrorContainer = Color(0xFFFFDAD6);
  static const Color darkBackground = Color(0xFF0F131C);
  static const Color darkOnBackground = Color(0xFFDFE2EF);
  static const Color darkSurfaceVariant = Color(0xFF31353F);
}
